### PR TITLE
Removed Radiation Dose and Radiation Duration per QDM 5.3

### PR DESCRIPTION
**Pull request by c-monkey**
See https://github.com/projecttacoma/cql_qdm_patientapi/pull/59 for details

### CODE REVIEW

**Comment by holmesie** [comment]
So this one is a bit confusing to me, and it's probably due to my unfamiliarity with this repository. It definitely looks like `Procedure, Recommended` doesn't have a `Radiation Dosage` or a `Radiation Duration` in the spec, but `Procedure, Performed` has both and `Procedure, Order` has `Radiation Duration`. This class looks like it covers all Procedure types though? Would we want to leave both of these in order to properly be able to handle `Procedure, Performed` and `Procedure, Order`?

**Comment by c-monkey** [comment]
See https://jira.mitre.org/browse/BONNIE-919 attachment for latest spec. "Radiation Dose" and "Radiation Duration" have been removed completely.

**Review by holmesie — APPROVED** [review]
Changes look good

**Review by mayerm94 — APPROVED** [review]
As long as these attributes only appear in the procedure datatype then these changes are good

**Comment by holmesie** [comment]
@mayerm94 Yeah, that's a good point. But it seems this repo doesn't even have a class for diagnostic study - which was the other datatype that had the radiation duration and dosage, so I think this covers what we needed 5.3 wise

**Comment by edeyoung** [comment]
For HDS and patientapi, some classes are hidden within other classes. it's probably word doing a "find" to confirm that the radiation dosage has actually been removed everywhere it's used.

**Comment by c-monkey** [comment]
@holmesie and @mayerm94 I have added unit tests. Please review.

**Comment by c-monkey** [comment]
For @edeyoung 's comment, since no existing measures use these attributes, my global removal of these 2 fields is exhaustive.

**Comment by edeyoung** [comment]
To support maintaining backwards compatibility, this change will not be incorporated. Instead, we'll add TODOs for what items should be removed for QDM 5.3. This will be a separate task.

**Pull request closed without merging**
