### PR TITLE
Prepare for Release 1.1

### PR DESCRIPTION
**Pull request by ssayer**
Prepare to publish gem v1.1

### CODE REVIEW

**Review by edeyoung — COMMENTED** [review]
bundle install is breaking for me on libv8. Probably an issue on my end, but would like to get that resolved monday morning before integrating this.

**Comment by ssayer** [comment]
I don't think that is a symptom of this update, as I've had versions of v8 fail to install on other projects. I've fixed it doing this:

gem install libv8 -v '3.16.14.11' -- --with-system-v8

(see https://stackoverflow.com/questions/19673714/error-installing-libv8-error-failed-to-build-gem-native-extension for reference)

But now that you mention that, I think that libv8 probably needs to be in the gemspec, however this would break the platform-ing that's done in the Gemfile. Rubygems requires different gems for each platform. Do you know if JRuby is still being used?

**Comment by edeyoung** [comment]
@hossenlopp is looking at updating libv8 to align with the version used by Bonnie.

When I run `bundle exec rake test` on this, it shows 0 tests being run and says `File does not exist: test/unit`. Thoughts?

I don't think this is related to this PR, however.

**Comment by edeyoung** [comment]
This PR is off of cql4bonnie. It should actually be off of master.

**Comment by ssayer** [comment]
Clsoing PR to issue new one off master

**Pull request closed without merging**
